version: "3"

services:
  web:
     build: .
     image: terra-ui
     links:
          - db
     ports:
          - 80:8090
     command: ["./wait-for-db.sh", "3306"]
    
  db:
     image: mysql
     environment:
          - MYSQL_ROOT_PASSWORD=mysql
          - MYSQL_DATABASE=terra
     expose:
          - 3306